
schema {
    query: Query
    mutation: Mutation
}

type Query {
    listarUsuarios: [Usuario]
    listarUsuarioPorId(id: Int): Usuario
    listarServicios: [Servicio]
    listarServicioPorId(id: Int): Servicio
    usuario(id: Int!): Usuario  # Cambiado getUsuario a usuario
}

type Mutation {
    crearUsuario(usuario: UsuarioInput!): Usuario
    crearServicio(nombre: String!, costo: Int!, direccion: String!): Servicio
    forgotPassword(email: String): Boolean
    updatePasswordByCode(code: String, password: String): Boolean
}

type Role {
    id: Int
    name: String
    usuarios:[Usuario]
}

input UsuarioInput {
    firstname: String!
    lastname: String!
    username: String!
    password: String!
    telephone: String!
    accountLocked: Boolean  # Corregido el tipo boolean
    enabled: Boolean  # Corregido el tipo boolean
    roles: [Int]
}

type Usuario {
    id: Int!
    firstname: String!
    lastname: String!
    username: String!
    password: String!
    telephone: String!
    accountLocked: Boolean
    enabled: Boolean
    roles: [Role]
}

type Servicio {
    id: Int
    nombre: String
    costo: Int
    direccion: String
}